Netatalk currently does not build against OpenSSL 1.1.0+, producing a half a dozen error messages like this:
error: dereferencing pointer to incomplete type 'DH {aka struct dh_st}'

This is caused by OpenSSL having made certain structs opaque, which forces
the library users to employ special getters and setters when accessing
these structs.
This PR makes Netatalk support the newest OpenSSL.