dhx uams: OpenSSL 1.1 support
Netatalk currently does not build against OpenSSL 1.1.0+,
producing a half a dozen error messages like this:

error: dereferencing pointer to incomplete type 'DH {aka struct dh_st}'

This is caused by OpenSSL having made certain structs opaque, which forces
the library users to employ special getters and setters when accessing
these structs.
This commit makes Netatalk support both old and new OpenSSL.

Bug: <https://github.com/Netatalk/Netatalk/issues/87>

Signed-off-by: Denis Bychkov <manover@gmail.com>
Reviewed-by: HAT <hat@fa2.so-net.ne.jp>
Reviewed-by: Ralph Boehme <slow@samba.org>